### PR TITLE
Smarter cache-buster for CSS

### PR DESCRIPTION
**Pull request by divergentdave**

### CODE REVIEW

**Comment by konklone** [comment]
I would like to see this done as part of `app/helpers.js`, so that it doesn't have to be added to every relevant view that renders the template. (Happy to do this myself tomorrow, too.)

**Comment by divergentdave** [comment]
:+1: we should factor out the report count too when doing so.

**Comment by konklone** [comment]
Looks like this had a dependency on the grunt-compiled `all.min.css` file. We're about to redo the CSS pipeline entirely, using `sass`, `bourbon`, and `neat`, but I'll point it at `main.css` for now.

**Comment by divergentdave** [comment]
Ah! I forgot to change it both places. Thanks.

**Comment by konklone** [comment]
OK, this added an `app/boot.js`, which is where ES connections happen now.

**Pull request merged**
