### PR TITLE
Index aliases

### LINKED ISSUE #26: Set up elasticsearch index aliases
Once the website is fully launched, and we start caring about uptime, we should change the scripts around to manage indexes through aliases. This is explained somewhere in the docs, but the general idea is that you give your real indexes numbered or versioned names and set up two aliases that point to numbered indexes, one for searching out of, and one for indexing into. Then you can make breaking changes in the write-only index, get it ready, and re-alias to make it provide searches.

### PR DESCRIPTION
**Pull request by divergentdave**
This will eventually fix #26

### CODE REVIEW

**Comment by konklone** [comment]
Still a WIP?

**Comment by divergentdave** [comment]
Yup, more yaks to shave yet

**Comment by divergentdave** [comment]
Okay, this should do for now. I haven't yet tested the fabfile changes.

**Comment by divergentdave** [comment]
One open question I have is whether it's reasonable to run a database reindex inside of a Fabric session. How long does that take? If it's way too long, we'll need to give the fabfile some awareness of what "versions" are on the server, so that we can do the first half of a deploy, disconnect and wait for the reindex to finish, and then connect later to move the symlinks and restart the service.

**Comment by konklone** [comment]
I think it's okay to include a reindex if it's generally expected to be fast, to only be slow when there's an interesting change, and for it not to be so slow that it's disruptive or can't be run in a single session. 

I don't know how long it will take to perform this kind of reindex though -- I haven't done index aliasing with ElasticSearch. Want to give it a try on the server and see how long it takes on the production dataset? It's still pretty low stakes and easy to re-index.

**Comment by divergentdave** [comment]
I don't think the index aliases should affect runtime, but I'm afraid that reindexing everything could take too long as it is. We'd only need to do so when making changes to the indexing options or database schema, which shouldn't be too often.

I tried running this on the production server, but I'm running into bizarre Ruby issues for now.

**Comment by divergentdave** [comment]
Got it working, the whole deploy/reindex process took `31m37.431s`. (for reference, deploying alone takes ~1min) This is kinda long, but good enough for now, I think.

I just pushed one more commit, this is good to go now!

**Comment by konklone** [comment]
It looks like the `reindex` task happens on every deploy? Is every deploy going to take 30 minutes now? I'm happy to merge, but unless I'm misreading that, I'd prefer that to be changed to only run when necessary.

**Comment by konklone** [comment]
Thank you for running all this down and doing such rigorous work!

**Comment by divergentdave** [comment]
Not every deploy, only if you choose `deploy_reindex` or `deploy_reindex_cold` as your entry point in fabfile.py. The `deploy` and `deploy_cold` entry points are unchanged, and we can keep using those two for almost all deploys, carrying the same index forward.

**Comment by konklone** [comment]
I read too fast! You're absolutely right, sorry.

**Pull request merged**
