### PR TITLE
Wintersmith deps fork

### PR DESCRIPTION
**Pull request by divergentdave**
Is this too crazy of an idea? Split from #111.

### CODE REVIEW

**Comment by konklone** [comment]
How much of the underlying security issues actually affect us? The way we're using Wintersmith, are affected by the XSS Markdown rendering hole?

**Comment by divergentdave** [comment]
The XSS bug is still there, but we don't pass any user input to it.

**Comment by konklone** [comment]
In your fork, or the original?

-- Eric

**Comment by divergentdave** [comment]
Oh, in the original. My fork of wintersmith pulls in `marked` from the PR
with the fix.

**Comment by konklone** [comment]
Since we're very unlikely to do a user blogging platform, I'm a little more
inclined to favor staying on the main branch than going to a personally
maintained fork. But if you feel otherwise, I'm fine with proceeding.

**Comment by konklone** [comment]
Is this moot now?

**Comment by divergentdave** [comment]
Yup, closing

**Pull request closed without merging**
