### PR TITLE
IPv6 support, take two

### PR DESCRIPTION
**Pull request by divergentdave**

### CODE REVIEW

**Comment by konklone** [comment]
:+1:

**Comment by divergentdave** [comment]
Safety not guaranteed, I still need to test this, and I'm not sure when
I'll get around to that.

**Comment by divergentdave** [comment]
Fixed a typo and added `::/0` to the EC2 security group, but this still isn't working yet.

**Comment by divergentdave** [comment]
So nginx is listening, the security group should be allowing traffic in and out, and the AAAA record is set, but the server still isn't reachable. Moreover, I SSH'd into the server and tried to reach ipv6.google.com from there, but that didn't work. Any ideas?

**Comment by konklone** [comment]
Might anything need to be done to the OS configuration itself to configure or open up IPv6 connections?

**Comment by divergentdave** [comment]
Maybe, though I'm not sure what, at this point. `ifconfig` says that it has an IPv6 address.

**Comment by divergentdave** [comment]
I added an IPv6 route to the internet gateway to the VPC's route table (thanks @ozzyjohnson!) but it still seems to be unreachable.

**Comment by divergentdave** [comment]
This is now complete and working. The last piece was to update the configuration under `/etc/network/interfaces.d/`. The configuration that the `cloud-init` package had built was not dual stack. See also http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-migrate-ipv6.html#ipv6-dhcpv6-ubuntu-16.

Many thanks to @ozzyjohnson and @krues8dr for advice. I'm going to merge this and do a clean deploy.

screenshot from 2017-07-09 23-07-38

**Comment by konklone** [comment]
Really, really nice job working through this, @divergentdave.

**Pull request merged**
