### PR TITLE
MVP for featured reports

### PR DESCRIPTION
**Pull request by konklone**
This adds a `config/featured.yaml` that contains a hash with `report_id`'s as keys. At index-time, if a report appears in the featured set, it has its metadata updated with the metadata about being featured.

It adds an `is_featured` boolean to the top level of each document, and a `featured` hash to the top level. The `featured` hash contains a `description`, an `author` name, and an `author_link`.

TODO: 

* [x] Move to global IDs (`inspector` + `report_id`) as index for `featured.yaml`, since `report_id` alone is not guaranteed to be unique.
* [x] Handle case where `featured` and `inspector` filters are both applied to a search.
* [x] Display the Featured metadata on the reports page for featured reports.
* [x] Change URL and give special presentation to `/reports/featured/`.
* [x] Add link on front page
* [x] Make sure the next/previous page links keep the featured filter

### CODE REVIEW

**Comment by divergentdave** [comment]
(っ^_^)っ here, have some commits

**Comment by konklone** [comment]
Nice. =)

I'd like to schedule another hack day, for myself anyway, to get this and other remaining nits done and shipped. It's clear that I'm not really capable of working on this in a steady background way anymore -- I need to plan the time.

**Comment by divergentdave** [comment]
Okay, the boxes are ticked on this! I'm up for reviewing and merging this now, then we can get into design next.

In particular, 2617195 displays the featured report metadata, but it does so using the same styling as highlights from report text. We should definitely differentiate the appearance of the two, but I think we should start with implementing Olivia's wireframes.

**Comment by konklone** [comment]
Everything works fine for me. I merged in the latest from `master`, and all looks good!

**Pull request merged**
