### PR TITLE
Upgrade to Elasticsearch 5.1

### PR DESCRIPTION
**Pull request by divergentdave**

### CODE REVIEW

**Comment by divergentdave** [comment]
Error message:

```
The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [text]
```

**Comment by divergentdave** [comment]
This is working well now in testing. Elastic really rolled a lot of breaking changes into version five. I think this is ready to deploy the next time I have a free evening. Plan:

* Create second AWS Elasticsearch domain, running version 5.1.1
* Tweak the per-node storage setting in the domain, as we did with the old one previously
  * For the record, our configuration currently looks like "Instance count: 1, Instance type: t2.small.elasticsearch, Storage type: EBS, EBS volume type: General Purpose (SSD), EBS volume size: 20GB, Automated snapshot start hour 00:00 UTC (default)"
  * The access policy attached to the domain allows "...:root" to perform "es:\*" actions on "...:domain/oversight/\*". (There's also an old clause with IP-based access from testing, but we don't need to carry that forward)
* Update user-data files with new DNS name for Elasticsearch domain
* Merge this PR to master (easier than juggling branches when deploying)
* Terminate the old scraper instance, start a new one, and SSH in
* Run the elasticsearch:init, elasticsearch:alias_write, elasticsearch:alias_read, and elasticsearch:init_dashboard rake tasks to prepare mappings
* Populate ES with `tasks/inspectors.js --since=1`
* Start a new web instance
* Kick the tires on staging.oversight.garden for a while
* Promote from staging to production when comfortable, terminate the old web instance when more comfortable, and delete the old AWS Elasticsearch domain when more comfortable still.

**Comment by konklone** [comment]
Big :+1: from me. Thank you so much for tackling this!

**Comment by divergentdave** [comment]
AWS now supports Elasticsearch 5.3. https://aws.amazon.com/about-aws/whats-new/2017/06/elasticsearch-5-3-now-available-on-amazon-elasticsearch-service/ I don't see any compelling features, so not upgrading.

**Pull request merged**
